#zeebe-broker:
#  gateway:
#    enable: true

#    network:
#      host: 0.0.0.0
#      port: 26500
#      minKeepAliveInterval: 30s

#    cluster:
#      requestTimeout: 15s

#    threads:
#      managementThreads: 1

#    monitoring:
#      enabled: false

#    security:
#      enabled: false
#      certificateChainPath:
#      privateKeyPath:

#  network:
#    host: 0.0.0.0
#    advertisedHost: 0.0.0.0
#    portOffset: 0
#    maxMessageSize: 4MB

#    commandApi:
#     host: localhost
#     port: 26501

#   internalApi:
#     host: localhost
#     port: 26502

#   monitoringApi:
#     host: localhost
#     port: 9600

# data:
#   directories: [ data ]
#   logSegmentSize: 512M
#   snapshotPeriod: 15m
#   maxSnapshots: 3

# cluster:
#   nodeId: 0
#   partitionsCount: 1
#   replicationFactor: 1
#   clusterSize: 1
#   initialContactPoints: []
#   clusterName: zeebe-cluster

# threads:
#   cpuThreadCount: 2
#   ioThreadCount: 2

#  exporters:
#    - id: debug-log
#      className: io.zeebe.broker.exporter.debug.DebugLogExporter
#      args:
#        logLevel: debug
#        prettyPrint: false
#    - id: debug-http
#      className: io.zeebe.broker.exporter.debug.DebugHttpExporter
#      args:
#        port: 8000
#        limit: 1024
#
#    - id: elasticsearch
#      className: io.zeebe.exporter.ElasticsearchExporter
#      args:
#        url: http://localhost:9200
#        bulk:
#         delay: 5
#         size: 1_000
#       authentication:
#         username: elastic
#         password: changeme
#       index:
#         prefix: zeebe-record
#         createTemplate: true
#         command: false
##        event: true
##        rejection: false
##        deployment: true
##        error: true
##        incident: true
#         job: true
#         jobBatch: false
#         message: false
#         messageSubscription: false
#         variable: true
#         variableDocument: true
#         workflowInstance: true
#         workflowInstanceCreation: false
#         workflowInstanceSubscription: false
